### ISSUE TITLE
Change layout (question)

### ISSUE THREAD

**Issue by joeydejong112** [hishizuka/pizero_bikecomputer#57]
Hi, i wanted to change the gui (layout) from the first screen with the power graph, in which file can i find this?

**Comment by hishizuka** [comment]
Hi @joeydejong112 ,
Thank you for using my program.

Oh, The power graph items require direct program modification.

FIrst, bring `PERFORMANCE_GRAPH` to the top in layout.yaml.

```
PERFORMANCE_GRAPH:
  STATUS: true

MAIN:
  STATUS: true
  LAYOUT:
    Power: [0, 0, 1, 2]
    HR: [0, 2]
    Speed: [1, 0]
    Cad.: [1, 1]
```

Second, modify L9-L12 of modules/pyqt/graph/pyqt_value_graph.py to change it to the item of your choice.

```
        "Power": (0, 0),
        "HR": (0, 1),
        "W'bal(Norm)": (0, 2),
        "LapTime": (0, 3),
```
